In [ ]:
import numpy as np
import sympy as sp
import time as tm

A = np.array([[1,1,0],
              [1,0,1],
              [0,1,0]])
B = np.array([[1,1,0,1],
              [1,0,1,0],
              [0,1,0,0],
              [0,1,0,0]])
b1 = np.array([[1],
              [2],
              [4]])
b2 = np.array([[1],
               [8],
               [4],
               [5]])

def CrammersRule(A,b):
    sol = []
    for i in range(len(b)):
        temp = A.copy()
        temp[:,i] = b[:,0]
        sol.append(round(np.linalg.det(temp)/np.linalg.det(A),1))
    return sol

InvA = np.linalg.inv(A)
InvASP = sp.Matrix(A).inv()
print(f"Inversa de A: \n {InvA}")
InvB = "no tiene inversa"
print(f"{InvB}")

DetA = np.linalg.det(A)
print(f"Determinante de A: {DetA}")
DetB = np.linalg.det(B)
print(f"Determinante de B: {DetB}\n")

print("Ax = b1")
SolInvNP = InvA.dot(b1)
print(f"Solucion con Inversa numpy: \n {SolInvNP}")

SolInvSP = InvASP*sp.Matrix(b1)
print(f"Solucion con inversa sympy: \n {SolInvSP}")

SolCrammer = CrammersRule(A, b1)
print(f"Solucion con Regla de Crammer:\n {SolCrammer} \n")

print("el sistema Bx = b2 no se puede solucionar con la inversa ni con crammer ya que su determinante es 0")



C = np.random.rand(100, 100)
d = np.random.rand(100, 1)
InvCNP = np.linalg.inv(C)
InvCSP = sp.Matrix(C).inv()

print("Cx = d")

start = tm.time()
SolInvNP = InvCNP.dot(d)
print(f"Solucion con Inversa numpy: \n {SolInvNP}")
print("Time: "+str(tm.time()-start)+"\n")

start = tm.time()
SolInvSP = InvCSP*sp.Matrix(d)
print(f"Solucion con inversa sympy: \n {SolInvSP}")
print("Time: "+str(tm.time()-start)+"\n")

start = tm.time()
SolCrammer = CrammersRule(C, d)
print(f"Solucion con Regla de Crammer:\n {SolCrammer}")
print("Time: "+str(tm.time()-start)+"\n")


D = np.random.rand(500, 500)
d2 = np.random.rand(500, 1)
InvCNP = np.linalg.inv(D)
InvCSP = sp.Matrix(D).inv()

print("Dx = d2")

start = tm.time()
SolInvNP = InvCNP.dot(d2)
print(f"Solucion con Inversa numpy: \n {SolInvNP}")
print("Time: "+str(tm.time()-start)+"\n")

start = tm.time()
SolInvSP = InvCSP*sp.Matrix(d2)
print(f"Solucion con inversa sympy: \n {SolInvSP}")
print("Time: "+str(tm.time()-start)+"\n")

start = tm.time()
SolCrammer = CrammersRule(D, d2)
print(f"Solucion con Regla de Crammer:\n {SolCrammer}")
print("Time: "+str(tm.time()-start)+"\n")




Inversa de A: 
 [[ 1.  0. -1.]
 [-0. -0.  1.]
 [-1.  1.  1.]]
no tiene inversa
Determinante de A: -1.0
Determinante de B: 0.0

Ax = b1
Solucion con Inversa numpy: 
 [[-3.]
 [ 4.]
 [ 5.]]
Solucion con inversa sympy: 
 Matrix([[-3], [4], [5]])
Solucion con Regla de Crammer:
 [-3.0, 4.0, 5.0] 

el sistema Bx = b2 no se puede solucionar con la inversa ni con crammer ya que su determinante es 0
Cx = d
Solucion con Inversa numpy: 
 [[ 0.66804843]
 [-2.1655284 ]
 [ 0.09135202]
 [-5.02887987]
 [-0.32608083]
 [ 1.97209629]
 [ 1.71624711]
 [ 1.83689423]
 [-2.04189051]
 [-1.25100192]
 [ 1.11244705]
 [ 0.41077796]
 [ 2.39234771]
 [ 0.22755907]
 [ 4.17472739]
 [ 0.42756645]
 [-0.1332467 ]
 [-2.83522256]
 [ 1.11645412]
 [-1.07493197]
 [ 1.71889783]
 [ 0.63698013]
 [-1.62952994]
 [ 1.85111216]
 [ 0.91296111]
 [-1.63530597]
 [ 0.10042165]
 [-2.33194794]
 [-1.05306746]
 [-2.70261035]
 [-3.05313294]
 [-1.22353154]
 [ 1.45982009]
 [ 0.71852143]
 [ 0.96868154]
 [ 1.39211609]
 [-2.23969954]
 [ 1.80114132]
